---

- hosts: localhost
  become: true
  vars_files:
    - vars.yml

  tasks:

  - name: Make Kibana available on all network interfaces
    lineinfile:
      path: /etc/kibana/kibana.yml
      regexp: '^server.host'
      line: 'server.host: "0.0.0.0"'

  - name: Create the Kibana logging directory
    file: path=/var/log/kibana/ state=directory owner=kibana group=kibana

  - name: Enable persistent Kibana logs
    lineinfile:
      path: /etc/kibana/kibana.yml
      regexp: '^logging.dest'
      line: 'logging.dest: /var/log/kibana/kibana.log'

  - name: Change Elasticsearch hosts
    lineinfile:
      path: /etc/kibana/kibana.yml
      regexp: 'elasticsearch.hosts'
      line: 'elasticsearch.hosts: ["http://127.0.0.1:9200"]'

  - name: Set Elasticsearch username 
    lineinfile:
      path: /etc/kibana/kibana.yml
      regexp: 'elasticsearch.username'
      line: 'elasticsearch.username: "kibana"'

  - name: Set Kibana user password 
    lineinfile:
      path: /etc/kibana/kibana.yml
      regexp: 'elasticsearch.password'
      line: 'elasticsearch.password: {{ kibana_user_password }}'

  - name: Start Kibana
    service: name=kibana state=restarted

  - name: Wait for Kibana to become available
    wait_for:
      port: 5601
      delay: 5
  
  - name: Wait for Kibana to be ready
    pause: 
      minutes: 2

  - name: Set dark mode
    uri:
      url: http://127.0.0.1:5601/api/kibana/settings/theme:darkMode
      user: elastic
      password: "{{ elastic_user_password }}"
      method: POST
      body: '{"value":"true"}'
      headers:
        Content-Type: "application/json"
        kbn-xsrf: true
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no

