---

- hosts: localhost
  become: true
  vars_files:
    - vars.yml

  tasks:

  - name: Change Logstash's minimum memory usage to 512MB
    lineinfile:
      path: /etc/logstash/jvm.options
      regexp: "^-Xms"
      line: "-Xms512m"
      state: present

  - name: Change Logstash's maximum memory usage to 512MB
    lineinfile:
      path: /etc/logstash/jvm.options
      regexp: "^-Xmx"
      line: "-Xmx512m"
      state: present

  - name: Add the Logstash configuration which activates monitoring
    template: src=templates/logstash/logstash.yml dest=/etc/logstash/logstash.yml

  - name: Add the Logstash input configuration for Beats
    template: src=templates/logstash/beats-input.conf dest=/etc/logstash/conf.d/00-beats-input.conf

  # - name: Add an empty Logstash filter configuration
  #   template: src=templates/logstash/empty-filter.conf dest=/etc/logstash/conf.d/11-my-filter.conf

  - name: Add the Logstash output configuration to Elasticsearch
    template: src=templates/logstash/elasticsearch-output.conf dest=/etc/logstash/conf.d/20-elasticsearch-output.conf

  - name: Change Elasticsearch output user password
    lineinfile:
      path: /etc/logstash/conf.d/20-elasticsearch-output.conf
      regexp: "password => x-pack-test-password"
      line: "password => {{ logstash_internal_password }}"
      state: present

  - name: Create the pattern directory
    file: path=/opt/logstash/patterns/ state=directory recurse=yes

  # - name: Add the workbook pattern, so we can use it later on
  #   template: src=templates/logstash/empty-pattern dest=/opt/logstash/patterns/mypattern

  - name: Start Logstash
    service: name=logstash state=restarted
